### ISSUE TITLE
is there a precompiled version of this ? or a begginers guide for comipling?

### ISSUE THREAD

**Issue by temp-defualt** [boundary/libdnet#5]
im trying to use this with scapy on win 7 x64 but failed to compile myself...

is there a begginers guide to compiling or even better a precompiled version?

**Comment by pbarry25** [comment]
+1 for Scapy.  We use mingw on an Ubuntu 14.04 system to build libdnet for Windows.  We statically link the resulting library into our agent.  FWIW, here's an example of the configure and make steps we use to build libdnet for 64-bit windows:

CC=x86_64-w64-mingw32-gcc RANLIB=x86_64-w64-mingw32-ranlib LDFLAGS="-L/home/code/builds/win32.x86_64/lib" CFLAGS="-g -O2" CPPFLAGS="-I/home/code/builds/win32.x86_64/include -DFD_SETSIZE=2048 -DWINVER=0x0502 -D_WIN32_WINNT=0x0502" /home/code/libdnet/configure --prefix=/home/code/builds/win32.x86_64 --host=x86_64-w64-mingw32 ac_cv_path_PKGCONFIG=/home/code/pkg-config --disable-shared ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes --with-wpdpack=/home/code/builds/win32.x86_64

make

**Comment by rgom** [comment]
Please refer to issue 4 (IIRC).
Contains patches and build instructions.

Robert

**Comment by temp-defualt** [comment]
HI all so we made one thanks for the great links and pointers ... 
This enabled us to run scapy on python 2.7 32bit with wifi support on windows!!!

Im attaching a pre compiled one.
[dnet.pyd.txt](https://github.com/boundary/libdnet/files/31388/dnet.pyd.txt)

 with instructions to compile and test bugs
[documentation.txt](https://github.com/boundary/libdnet/files/31391/documentation.txt)

 works great on win xp till windows 10 (currently tested on 5 different machines and 20 VMs) now in active use ill update here if any bugs will be found...

and finally for those who wish to compile their own
[fix-intf-win32.patch.txt](https://github.com/boundary/libdnet/files/31392/fix-intf-win32.patch.txt)

Hope This Helps 
temp.defualt [A T] gmail [D O T] ...
